# Generated by Django 4.0.5 on 2022-07-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issues',
            options={},
        ),
        migrations.RemoveField(
            model_name='issues',
            name='Issue_Solver',
        ),
        migrations.AddField(
            model_name='issues',
            name='Issue_Approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
