# Generated by Django 4.0.5 on 2022-07-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srs', '0002_alter_issues_options_remove_issues_issue_solver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='Issue',
            field=models.BooleanField(default=True),
        ),
    ]
